"use strict";
let bike = "honda";
console.log(`Is bike == "honda"? I predict true`);
console.log(bike == "honda");
console.log(`Is bike != "honda"? I predict false`);
console.log(bike != "honda");
console.log(`Is bike == "Honda"? I predict false`);
console.log(bike == "Honda");
console.log(`Is bike != "Honda"? I predict true`);
console.log(bike != "Honda");
console.log(`Is bike == "yamaha"? I predict false`);
console.log(bike == "yamaha");
console.log(`Is bike != "yamaha"? I predict true`);
console.log(bike != "yamaha");
console.log(`Is bike == "HONDA"? I predict false`);
console.log(bike == "HONDA");
console.log(`Is bike != "HONDA"? I predict true`);
console.log(bike != "HONDA");
console.log(`Is bike == "unique"? I predict false`);
console.log(bike == "unique");
console.log(`Is bike != "unique"? I predict true`);
console.log(bike != "unique");
